// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlIe0EhrJm6VTmenPX061Ub3ctB8Voscg',
    appId: '1:561734449423:web:c8d180bcedc6fdd805e67a',
    messagingSenderId: '561734449423',
    projectId: 'home-market-9a104',
    authDomain: 'home-market-9a104.firebaseapp.com',
    databaseURL: 'https://home-market-9a104-default-rtdb.firebaseio.com',
    storageBucket: 'home-market-9a104.appspot.com',
    measurementId: 'G-9MPHXB2F6M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo0KneuHmc6Vt3MTeyoFjAofj2iCQMtBA',
    appId: '1:561734449423:android:39b88f285e56b25705e67a',
    messagingSenderId: '561734449423',
    projectId: 'home-market-9a104',
    databaseURL: 'https://home-market-9a104-default-rtdb.firebaseio.com',
    storageBucket: 'home-market-9a104.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9iWSgrqUfWsQ9iNY_MKVYl6Z0bZNXHgU',
    appId: '1:561734449423:ios:cf2a3350364e3fd205e67a',
    messagingSenderId: '561734449423',
    projectId: 'home-market-9a104',
    databaseURL: 'https://home-market-9a104-default-rtdb.firebaseio.com',
    storageBucket: 'home-market-9a104.appspot.com',
    iosBundleId: 'com.example.homeMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9iWSgrqUfWsQ9iNY_MKVYl6Z0bZNXHgU',
    appId: '1:561734449423:ios:79f925b35a6ec19d05e67a',
    messagingSenderId: '561734449423',
    projectId: 'home-market-9a104',
    databaseURL: 'https://home-market-9a104-default-rtdb.firebaseio.com',
    storageBucket: 'home-market-9a104.appspot.com',
    iosBundleId: 'com.example.homeMarket.RunnerTests',
  );
}
